version: "3"

services:
  tm-phoenix:
    container_name: tm-phoenix
    build: ./elixir/.
    volumes:
      - ./elixir:/app
    ports:
      - "4000:4000"
    depends_on:
      - tm-db
    networks:
      - time-manager

  tm-db:
    container_name: tm-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data*
    networks:
      - time-manager

networks:
  time-manager:
    name: time-manager